### PR TITLE
Issue # 68. changed prompt from 'startBundle' to 'conduct start'

### PR DESCRIPTION
**Pull request by dsugden**
sorry about that (git rebase etc.)

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, thanks!

Resolves https://github.com/sbt/sbt-conductr/issues/68

**Comment by 2m** [comment]
ConductR python CLI [has run command](https://github.com/typesafehub/typesafe-conductr-cli/blob/f55c3ee7984a336f36937b97e69d5512c26aaf19/typesafe_conductr_cli/conduct.py#L82-L92) for running a bundle. Could you amend this PR to make it consistent?

**Comment by hseeberger** [comment]
Or vice versa? I think start is a better name.

**Comment by 2m** [comment]
It used to be start. But [we have changed](https://github.com/typesafehub/typesafe-conductr-cli/commit/525ba34bc3e744df5ab650288e3e3f1921f197d9) it to run. :) Do you remember the reason? Is it still valid?

**Comment by hseeberger** [comment]
That's not fair ;-)

**Comment by dsugden** [comment]
heh, I'm good with whatevs.  Maybe the renaming if it happens should be a different PR though.

**Comment by huntc** [comment]
Please change it to _run_

**Pull request merged**
